### PR TITLE
Win32: Implement socket: plugins in build.js for each platform

### PR DESCRIPTION
**Pull request by mribbons**

### CODE REVIEW

**Review by chicoxyzzy — CHANGES_REQUESTED** [review]
This introduces a new complexity of a build step. We should avoid this and make the `socket:*` imports work reliably.

**Comment by mribbons** [comment]
> This introduces a new complexity of a build step. We should avoid this and make the `socket:*` imports work reliably.

Hey @chicoxyzzy, I just used the approach from the test app, what is the reliable approach?
https://github.com/socketsupply/socket/blob/master/test/build.js#L43

@jwerle can you recall why it was implemented this way?

**Comment by chicoxyzzy** [comment]
> what is the reliable approach?

WebView2 has import maps support so the custom imports should just work

**Comment by mribbons** [comment]
> WebView2 has import maps support so the custom imports should just work
@chicoxyzzy Can you point me to how this is handled in one of the other OS's?

**Comment by chicoxyzzy** [comment]
I found the usage of `importmap.json` only in Android code but I'm not sure if that actually works cc @jwerle.
Import maps were implemented in WebKit just recently. They are available in Safari 16.4 beta and Safari TP so we need to wait until they are added to the WebKit stable on all the platforms. We use the `socket:` protocol and this code in the bridge `https://github.com/socketsupply/socket/blob/master/src/ipc/bridge.cc#L1276-L1311`

I think that we can add something like this to the head of the `index.html` on Windows to make import maps work:
```html
<script type="importmap" src="socket/importmap.json"></script>
```

**Comment by jwerle** [comment]
> I found the usage of `importmap.json` only in Android code but I'm not sure if that actually works cc @jwerle. Import maps were implemented in WebKit just recently. They are available in Safari 16.4 beta and Safari TP so we need to wait until they are added to the WebKit stable on all the platforms. We use the `socket:` protocol and this code in the bridge https://github.com/socketsupply/socket/blob/master/src/ipc/bridge.cc#L1276-L1311
> 
> I think that we can add something like this to the head of the `index.html` on Windows to make import maps work:
> 
> ```
> <script type="importmap" src="socket/importmap.json"></script>
> ```

Yep they work in Android. I inject it into the head. We can do the same for Window

**Comment by mribbons** [comment]
@jwerle: This?

https://github.com/socketsupply/socket/blob/master/src/window/linux.cc#L564-L573

```cpp
    webkit_user_content_manager_add_script(
      manager,
      webkit_user_script_new(
        preload.c_str(),
        WEBKIT_USER_CONTENT_INJECT_TOP_FRAME,
        WEBKIT_USER_SCRIPT_INJECT_AT_DOCUMENT_START,
        nullptr,
        nullptr
      )
    );
```

**Comment by mribbons** [comment]
@jwerle on Android you are passing the enitre html string, but windows accepts a URL parameter:
```cpp
// window/win.cc
webview->Navigate(SSC::StringToWString(value).c_str());
// WebView2.h
virtual HRESULT STDMETHODCALLTYPE Navigate( 
            /* [in] */ LPCWSTR uri) = 0;
```
What do you think about injecting the importmap in `createPreload`, for now just #ifdef WIN32?

Also, how does it work on other platforms? I can't find any other references to importmap outside of `window.kt` and `install.sh`

**Comment by jwerle** [comment]
android is the only place we do that as importmaps do not work on webkit (linux, macos, ios). They should work on WebView2 as it is based on chromium too. We'd need to inject this to be evaluated before any other script is, ideally inlined in the HTML

**Comment by mribbons** [comment]
@jwerle I tried inserting it within preload, but either head doesn't exist yet, or it gets executed too late in `DOMContentLoaded`

So I just tried manually importing it which doesn't work ('currently external imports are not supported')

inlining does work though 🎉 . This will mean something in `build.js` like:
```js
if (os.platform() !== 'win32') {
   // modify index.html
}
```
We're also going to have to ship `importmap.json`, or `bin/generate-api-import-map.sh`.

**Comment by chicoxyzzy** [comment]
Preload is a JavaScript code in non-ESM format and Import Map is a JSON which should be placed in the HTML `<head>` before any other `<script>` tags. We can't place Import Maps in the preload script.

**Comment by chicoxyzzy** [comment]
> This will mean something in `build.js` 

`build.js` is a custom userland code and it is optional. We should either put the `<script type="importmap" src="socket/importmap.json"></script>` in the head for all the files in the same way we do it for CSP or patch HTML files before `navigate`. If we are going to patch before `navigate`, we probably should do the same for CSP.

One thing I don't understand is how the test app works on Windows without import maps.

**Comment by chicoxyzzy** [comment]
oh I see that we patch imports in the `build.js` there

**Comment by chicoxyzzy** [comment]
> android is the only place we do that as importmaps do not work on webkit

I though that Android uses WebKit too. I see many references of `android.webkit` in the Kotlin code

**Comment by mribbons** [comment]
@chicoxyzzy I tested manually inlining it into index.html on mac, doesn't cause any issues.

**Comment by chicoxyzzy** [comment]
@mribbons the `importmap` script? Does your system have Safari 16.4 beta installed?

**Comment by mribbons** [comment]
@chicoxyzzy 

I'll get 16.4b.

```html
    >
    <title>Vite + Svelte</title>
    <script type="jsonimport">
      {
        "imports": {
           "socket:application": "./socket/application.js",
           "socket:backend": "./socket/backend.js",
           "socket:bluetooth": "./socket/bluetooth.js",
           "socket:bootstrap": "./socket/bootstrap.js",
           "socket:buffer": "./socket/buffer.js",
           "socket:console": "./socket/console.js",
// .....
</script>
```

**Comment by chicoxyzzy** [comment]
what is `jsonimport` type?

**Comment by mribbons** [comment]
> what is `jsonimport` type?

Great question, it also works with `importmap`

**Comment by mribbons** [comment]
socket: scheme implemented for Win32

**Comment by mribbons** [comment]
socket: scheme implemented for Win32

**Pull request closed without merging**
