### PR TITLE
Adding information colors to CSA app initialization process.

### PR DESCRIPTION
**Pull request by wujekbizon**
CSA (create-socket-app) initialization process, works like a charm. I thought it might be a good idea to add, information colors, to better show the output of the process, to anyone who will use CSA. Something like the pic below: 
sampleimage

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Hmm Chalk has no dependancies, so I think we can consider using it. Although I prefer using emojis so no extra code is needed to shipped and no extra dependancy which could be a potential security risk :)
Lets see what other think

**Comment by chicoxyzzy** [comment]
BTW the screenshot is just a transparent layer for me for some reason

**Comment by wujekbizon** [comment]
> Hmm Chalk has no dependancies, so I think we can consider using it. Although I prefer using emojis so no extra code is needed to be shipped and no extra dependancy which could be a potential security risk :) Lets see what others think

chalk

**Comment by mribbons** [comment]
Hey @wujekbizon,
I'm with @chicoxyzzy, Socket Supply has a no deps philosophy, and I don't think colored output would be a good enough reason to break on that.
Feel free to submit a PR for emojis.
What I think would be a better approach than sprinkling the color or emoji functions throughout the stdout.write() code, is to have some standard functions like writeSuccess(), writeProgress(), writeError(), and each of those would implement context specific styling, or to pass a style param to a single writeStyled() function.
If you don't want to go to the trouble of submitting everything in a perfect PR, feel free to write up some gists showing sample output and a subset of the required changes.

**Comment by wujekbizon** [comment]
I'm completely understand and I also want to follow Socket Supply no deps philosophy , so let's for now close this PR and I'll get back to it later. @mribbons I like your idea of writeStyled() function, so maybe when the time's come, I can help you, to implement it.

**Pull request closed without merging**
